[2025-08-14T17:46:32.695+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-14T17:46:32.703+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pg_extra_create_and_log.log_data manual__2025-08-14T17:46:29.672369+00:00 [queued]>
[2025-08-14T17:46:32.705+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pg_extra_create_and_log.log_data manual__2025-08-14T17:46:29.672369+00:00 [queued]>
[2025-08-14T17:46:32.705+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-14T17:46:32.708+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): log_data> on 2025-08-14 17:46:29.672369+00:00
[2025-08-14T17:46:32.710+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=349) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-14T17:46:32.711+0000] {standard_task_runner.py:63} INFO - Started process 350 to run task
[2025-08-14T17:46:32.711+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pg_extra_create_and_log', 'log_data', 'manual__2025-08-14T17:46:29.672369+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpwfantf7u']
[2025-08-14T17:46:32.711+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask log_data
[2025-08-14T17:46:32.724+0000] {task_command.py:426} INFO - Running <TaskInstance: pg_extra_create_and_log.log_data manual__2025-08-14T17:46:29.672369+00:00 [running]> on host 1ed929767bb5
[2025-08-14T17:46:32.747+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pg_extra_create_and_log' AIRFLOW_CTX_TASK_ID='log_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T17:46:29.672369+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T17:46:29.672369+00:00'
[2025-08-14T17:46:32.748+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-14T17:46:32.753+0000] {base.py:84} INFO - Using connection ID 'pg_extra_conn' for task execution.
[2025-08-14T17:46:32.755+0000] {logging_mixin.py:188} INFO - Содержимое таблицы sample_data:
[2025-08-14T17:46:32.755+0000] {logging_mixin.py:188} INFO - (1, 'alpha', 10)
[2025-08-14T17:46:32.755+0000] {logging_mixin.py:188} INFO - (2, 'beta', 20)
[2025-08-14T17:46:32.755+0000] {logging_mixin.py:188} INFO - (3, 'gamma', 30)
[2025-08-14T17:46:32.755+0000] {logging_mixin.py:188} INFO - (4, 'alpha', 10)
[2025-08-14T17:46:32.755+0000] {logging_mixin.py:188} INFO - (5, 'beta', 20)
[2025-08-14T17:46:32.756+0000] {logging_mixin.py:188} INFO - (6, 'gamma', 30)
[2025-08-14T17:46:32.756+0000] {logging_mixin.py:188} INFO - (7, 'alpha', 10)
[2025-08-14T17:46:32.756+0000] {logging_mixin.py:188} INFO - (8, 'beta', 20)
[2025-08-14T17:46:32.756+0000] {logging_mixin.py:188} INFO - (9, 'gamma', 30)
[2025-08-14T17:46:32.756+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-14T17:46:32.756+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-14T17:46:32.759+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pg_extra_create_and_log, task_id=log_data, run_id=manual__2025-08-14T17:46:29.672369+00:00, execution_date=20250814T174629, start_date=20250814T174632, end_date=20250814T174632
[2025-08-14T17:46:32.769+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-14T17:46:32.774+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T17:46:32.774+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
