[2025-08-26T13:02:34.341+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-26T13:02:34.348+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generated_py_do_something.first_task manual__2025-08-26T13:02:32.438368+00:00 [queued]>
[2025-08-26T13:02:34.350+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generated_py_do_something.first_task manual__2025-08-26T13:02:32.438368+00:00 [queued]>
[2025-08-26T13:02:34.350+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-26T13:02:34.354+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): first_task> on 2025-08-26 13:02:32.438368+00:00
[2025-08-26T13:02:34.356+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=194) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-26T13:02:34.356+0000] {standard_task_runner.py:63} INFO - Started process 195 to run task
[2025-08-26T13:02:34.357+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'generated_py_do_something', 'first_task', 'manual__2025-08-26T13:02:32.438368+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpggmvnub5']
[2025-08-26T13:02:34.357+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask first_task
[2025-08-26T13:02:34.371+0000] {task_command.py:426} INFO - Running <TaskInstance: generated_py_do_something.first_task manual__2025-08-26T13:02:32.438368+00:00 [running]> on host 1ed929767bb5
[2025-08-26T13:02:34.394+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generated_py_do_something' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-26T13:02:32.438368+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-26T13:02:32.438368+00:00'
[2025-08-26T13:02:34.394+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-26T13:02:34.398+0000] {logging_mixin.py:188} INFO - Начало работы ДАГа
[2025-08-26T13:02:34.398+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-26T13:02:34.399+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-26T13:02:34.401+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=generated_py_do_something, task_id=first_task, run_id=manual__2025-08-26T13:02:32.438368+00:00, execution_date=20250826T130232, start_date=20250826T130234, end_date=20250826T130234
[2025-08-26T13:02:34.414+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-26T13:02:34.422+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-26T13:02:34.422+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
