[2025-08-26T13:02:35.058+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-26T13:02:35.065+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generated_py_do_something.my_function manual__2025-08-26T13:02:32.438368+00:00 [queued]>
[2025-08-26T13:02:35.067+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generated_py_do_something.my_function manual__2025-08-26T13:02:32.438368+00:00 [queued]>
[2025-08-26T13:02:35.067+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-26T13:02:35.071+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): my_function> on 2025-08-26 13:02:32.438368+00:00
[2025-08-26T13:02:35.073+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=196) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-26T13:02:35.073+0000] {standard_task_runner.py:63} INFO - Started process 197 to run task
[2025-08-26T13:02:35.074+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'generated_py_do_something', 'my_function', 'manual__2025-08-26T13:02:32.438368+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpnueex7bp']
[2025-08-26T13:02:35.074+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask my_function
[2025-08-26T13:02:35.087+0000] {task_command.py:426} INFO - Running <TaskInstance: generated_py_do_something.my_function manual__2025-08-26T13:02:32.438368+00:00 [running]> on host 1ed929767bb5
[2025-08-26T13:02:35.110+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generated_py_do_something' AIRFLOW_CTX_TASK_ID='my_function' AIRFLOW_CTX_EXECUTION_DATE='2025-08-26T13:02:32.438368+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-26T13:02:32.438368+00:00'
[2025-08-26T13:02:35.110+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-26T13:02:35.114+0000] {logging_mixin.py:188} INFO - Doing something inside AirFlow!
[2025-08-26T13:02:35.114+0000] {logging_mixin.py:188} INFO - Step: 0
[2025-08-26T13:02:35.114+0000] {logging_mixin.py:188} INFO - No data!
[2025-08-26T13:02:35.114+0000] {logging_mixin.py:188} INFO - Step: 2
[2025-08-26T13:02:35.114+0000] {logging_mixin.py:188} INFO - No data!
[2025-08-26T13:02:35.114+0000] {logging_mixin.py:188} INFO - Step: 4
[2025-08-26T13:02:35.115+0000] {logging_mixin.py:188} INFO - No data!
[2025-08-26T13:02:35.115+0000] {logging_mixin.py:188} INFO - Step: 6
[2025-08-26T13:02:35.115+0000] {logging_mixin.py:188} INFO - No data!
[2025-08-26T13:02:35.115+0000] {logging_mixin.py:188} INFO - Step: 8
[2025-08-26T13:02:35.115+0000] {logging_mixin.py:188} INFO - No data!
[2025-08-26T13:02:35.115+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-26T13:02:35.115+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-26T13:02:35.117+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=generated_py_do_something, task_id=my_function, run_id=manual__2025-08-26T13:02:32.438368+00:00, execution_date=20250826T130232, start_date=20250826T130235, end_date=20250826T130235
[2025-08-26T13:02:35.132+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-26T13:02:35.138+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-26T13:02:35.139+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
