[2025-08-26T13:02:33.208+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-26T13:02:33.216+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generated_py_do_something.f_task manual__2025-08-26T13:02:32.438368+00:00 [queued]>
[2025-08-26T13:02:33.218+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generated_py_do_something.f_task manual__2025-08-26T13:02:32.438368+00:00 [queued]>
[2025-08-26T13:02:33.218+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-26T13:02:33.223+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): f_task> on 2025-08-26 13:02:32.438368+00:00
[2025-08-26T13:02:33.225+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=192) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-26T13:02:33.225+0000] {standard_task_runner.py:63} INFO - Started process 193 to run task
[2025-08-26T13:02:33.226+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'generated_py_do_something', 'f_task', 'manual__2025-08-26T13:02:32.438368+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9flttcbx']
[2025-08-26T13:02:33.226+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask f_task
[2025-08-26T13:02:33.241+0000] {task_command.py:426} INFO - Running <TaskInstance: generated_py_do_something.f_task manual__2025-08-26T13:02:32.438368+00:00 [running]> on host 1ed929767bb5
[2025-08-26T13:02:33.268+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generated_py_do_something' AIRFLOW_CTX_TASK_ID='f_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-26T13:02:32.438368+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-26T13:02:32.438368+00:00'
[2025-08-26T13:02:33.268+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-26T13:02:33.272+0000] {logging_mixin.py:188} INFO - Начало работы ДАГа
[2025-08-26T13:02:33.272+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-26T13:02:33.273+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-26T13:02:33.275+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=generated_py_do_something, task_id=f_task, run_id=manual__2025-08-26T13:02:32.438368+00:00, execution_date=20250826T130232, start_date=20250826T130233, end_date=20250826T130233
[2025-08-26T13:02:33.283+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-26T13:02:33.291+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-26T13:02:33.292+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
